services:
  - type: web
    name: foodbridge
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && python ml/model.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
